name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 730335665993.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Build Docker image
        run: |
          docker build -t grupopag/pag-restaurante-api:latest .
          docker tag grupopag/pag-restaurante-api:latest 730335665993.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/grupopag/pag-restaurante-api:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 730335665993.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/grupopag/pag-restaurante-api:latest

      # Adiciona o passo para chamar o webhook ao final
      - name: Notify Webhook
        if: success() # Executa este passo apenas se os passos anteriores tiverem sucesso
        run: curl -X POST https://webhook.grupopag.com/hooks/docker-update
